[Feat/socket handler] 소켓 에러 핸들리 - 기존 핸들러 수정, Controller 단 핸들러 추가 구현
Run-Us/Run-Us-server pull request #34
Opened 2024-10-16 10:06 UTC by jeeheaG

### 연관된 이슈를 적어주세요 📌
x

### 작업한 내용을 설명해주세요 ✔️
- `GlobalSocketExceptionHandler` : 소켓 컨트롤러 단 에러 핸들러 구현
  - 여기서도 `sendToUser` 기능이 필요한데, 로직이 중복으로 여기저기 생기는 기분이라 특정유저에게 소켓응답해주는 부분을 모듈화하면 어떨까..? 생각해보고 있습니다. 
  전에 비슷한 경험으로 다른 프로젝트에서 소켓 응답 전송하는 부분들만 `~SocketResponser` 라는 이름의 클래스로 모아둔 적이 있어요. 꽤 괜찮았어서 `sendToUser` 메서드 빼놓는 것도 나쁘지 않을 것 같다는 생각이 들어요.
- `StompErrorHandler` : intercpetor 단에서 발생하는 에러 핸들링 후 연결 끊기지 않도록 변경
   - ERROR 프레임으로 응답되어 연결이 끊김 -> MESSAGE 로 응답되도록 변경
   - 에러가 잡혔을 때 어떤 에러인지 판단하는 부분만 기존 핸들러 `StompErrorHandler`에 남기고, 각 에러별 처리 로직을 담을 핸들러 클래스를 별도로 구현하여 분리
   - `SocketExceptionCustomHandler` : 처리 로직을 담는 핸들러들의 인터페이스
   - `SocketBusinessExceptionHandler` : 처리 로직을 담는 핸들러. `BusinessException` 만을 처리함
   지금 저희가 `BusinessException` 을 최상위 커스텀 예외로 사용하고 있어서 일단 그것만 구현했습니다.
   추후에 저희 커스텀 예외마다 다른 처리를 해줘야 하는 상황이 오면, 해당 핸들러는 제거하고 대신 이를 참고해 예외 별 처리 핸들러들을 만들어주면 됩니다.
  그냥 `StompErrorHandler` 에서 if 문 분기시킬까 하다가.. 나중에 지저분해질 거 같아서 분리해봤습니다
- 그리고 몇가지 상수값들 Const화 했어요
- `TestController` : 에러 발생시키는 요청 두개 만들었습니다. 테스트에 사용해주셔도 됩니다.

### 트러블 슈팅
x

### 리뷰어에게 하고 싶은 말을 적어주세요
에러 응답 실행 모습

- interceptor 단 에러
![interceptor 단 에러 응답](https://github.com/user-attachments/assets/6334b977-5465-4071-ab23-a2b0bc86cff5)

- controller 이후 단 에러
![controller 단 에러 응답](https://github.com/user-attachments/assets/c45e7c51-1fad-4696-80e6-f17942f28e69)

이렇게 오게 했습니다. body 를  json 으로 변경했어요
intercpetor 단 에러 응답 헤더가 비어보여서 뭐라도 넣을까하다가 딱히.. 필요성이 안느껴져서 일단 이렇게만 구현했습니다.

- sendToUser 모듈화는 어떻게 생각하시나요?

### 확인하기

- [ ] : 코드에 에러가 없는지 확인했나요?
- [ ] : PR에 설명을 기재했나요?
- [ ] : PR 태그를 붙였나요?
- [ ] : 불필요한 로그나 `System.out`을 제거했나요?

2024-10-16 11:42 UTC, ekgns33 requested changes

2024-10-16 11:42 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/exception/GlobalSocketExceptionHandler.java
> +    private void sendToUser(@NotNull String sessionId, @NotNull String destination, Object payload) {
임시방편으로 이렇게 했었는데 아마 기존 `@SendToUser` 해결책이 있을 것 같아유.
 제가 코드를 좀 보고있는데 일단 이렇게 두고, 기존에 있는 어노테이션 사용가능해지면 그냥 어노테이션으로 가면 될 것 같습니다.

2024-10-16 11:42 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/exception/SocketBusinessExceptionHandler.java
> +public class SocketBusinessExceptionHandler implements SocketExceptionCustomHandler {
결국 에러메세지가 아니라 메세지로 줘야하는게 정답이었군요. 어차피 코드로 구분가능하니 괜찮아보이네요

2024-10-16 11:42 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/exception/SocketExceptionCustomHandler.java
> +     * @return 해당 ㅇ외 처리 가능여부
오타 수정 부탁드립니다~

2024-10-16 11:42 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
> +        for(SocketExceptionCustomHandler handler : handlers) {
뭔가 핸들러라는 이름보다 필터에 가까운것 같은데 어떤가요? 핸들러는 에러를 받은 현재 객체가 담당하고 에러별로 로직을 수행하는 것도 핸들러라고 불러야할지 의문이네요.

2024-10-17 14:30 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/exception/SocketExceptionCustomHandler.java
> +     * @return 해당 ㅇ외 처리 가능여부
아이쿠 감사합니다!

2024-10-17 14:31 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
> +        for(SocketExceptionCustomHandler handler : handlers) {
음.. 저도 이거 고민하긴 했는데 그럼 인터셉터에서 쓰는 거니까 인터셉터로 갈까요?
-> `SocketExceptionCustomInterceptor`

2024-10-17 14:33 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/exception/GlobalSocketExceptionHandler.java
> +    private void sendToUser(@NotNull String sessionId, @NotNull String destination, Object payload) {
넵 가능한 어노테이션 도입하는 방향으로..

2024-10-17 15:34 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/exception/StompErrorHandler.java
> +        for(SocketExceptionCustomHandler handler : handlers) {
원하시는 방향으로 하셔도 될 것 같습니다! 의미론적으로 둘다 맞아보이네오 ㅋㅋ

2024-10-18 16:42 UTC, merged