[Refactor/erd-sync] ERD에 맞게 타입 싱크
Run-Us/Run-Us-server pull request #37
Opened 2024-10-25 07:14 UTC by hughesgoon

### 연관된 이슈를 적어주세요 📌

### 작업한 내용을 설명해주세요 ✔️

- ERD에 맞추어 (많은 클래스의) 타입 수정
  - id는 모두 Integer
  - public_id는 char(13)
- 유저, 프로필 테이블을 가져오기 위해 급히 프로필 분리
  - 테스트 코드도 이에 맞게 프로필과 유저 객체 활용하도록 적용

### 트러블 슈팅

### 리뷰어에게 하고 싶은 말을 적어주세요

- 사실 유저에서 프로필 요소를 바로 쓰고싶었으나 제 JPA 실력이 부족하여 OneToOne을 썼읍니다... 나는 필요하다. 좋은 방법.
- 아마 코드 건든게 많아서 충돌은 많이 날텐데, 타입변환만 잘 맞춰주면 로직상 이슈는 (아마)(거의) 없을겁니다.

### 확인하기

- [x] : 코드에 에러가 없는지 확인했나요?
- [x] : PR에 설명을 기재했나요?
- [x] : PR 태그를 붙였나요?
- [x] : 불필요한 로그나 `System.out`을 제거했나요?

2024-10-25 09:01 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/user/repository/UserRepository.java
> +  @Query("SELECT p FROM Profile p JOIN FETCH p.user u WHERE p.nickname = :nickname AND u.deletedAt IS NULL")
N+1걱정했는데 페치조인으로 처리하셨군요 👍

2024-10-25 09:17 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/user/domain/User.java
> +  @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
- USER에서 FK를 들고 USER가 Profile을 수정하게끔 바꾸는게 어떨까요?

우리 데이터베이스에서는 유저의 FK를 프로필이 들고 있는데 이렇게하면 NULL을방지하기도하고... ERD관점에서는 좋습니다. 
다만 FK를 Profile에서 들고있게되면, Lazy fetch가 불가능해지는 것으로 알고있습니다.. 무조건 EAGER로 걸릴거에여. 

패러다임의 불일치가 있지만 USER에서 FK를 들고있으면 편해지는 것들이 많아서 설계를 수정하는 게 어떨까요? NULL문제는 회원가입시에 입력받는데이터를 바로 Profile로 만들어 같이 저장하면 시스템의 흐름상 NULL을 막을 수 있지 않을까요?

2024-10-25 09:18 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
> +public abstract class CreationTimeAudit implements Serializable {
이건 기존의 친구는 update를 비롯한 데이터를 함께 저장해서 새로 만드신건가요?

2024-10-25 09:18 UTC, ekgns33 reviewed
고생하셨어요! JPA이슈하나 달아놨습니다!

2024-10-25 09:26 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
저도 id 는 Long 으로 썼었는데 이유 궁금합니담

2024-10-25 10:06 UTC, jeeheaG approved these changes
고생하셨습니다~!

2024-10-25 10:06 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
> +public abstract class CreationTimeAudit implements Serializable {
다훈님이 말씀하신 의미가 맞다면~ 기존에 있던 DateAudit 랑 이름을 비슷하게 맞춰주면 좋을 것 같습니다.
CreateDateAudit 라던지?

2024-10-25 10:06 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
>        throw new IllegalArgumentException("총 거리는 0 이상이어야 합니다.");
이번 변경사항은 아니긴 한데 여기 커스텀 Exception 안쓰신 이유가 있나요?

2024-10-25 11:34 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
> +public abstract class CreationTimeAudit implements Serializable {
다훈님이 말씀하신 의미가 맞다면
기존 DateAudit 랑 이름을 비슷하게 맞춰주면 어떨까요?
CreateDateAudit 라던지..?

2024-10-25 13:47 UTC, hughesgoon commented on src/main/java/com/run_us/server/global/common/CreationTimeAudit.java
> +public abstract class CreationTimeAudit implements Serializable {
요거 솔직히 DateAudit이라 맞추려다 뭔가 이게 date인가 time인가 인지부조화가 걸려서 👀
좋은 이름 추천받습니다,,, (1번 후보군 CreateDateAudit)

2024-10-25 14:01 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/RunningRecord.java
>        throw new IllegalArgumentException("총 거리는 0 이상이어야 합니다.");
어 에 어,,, 타입변환 외에 신경쓰지 않았읍니다,,,, 생각을,, 해봤어야했는데 무지성 디버깅하다가,,,
`git blame` @ekgns33  선생님께 토스 ㅎㅅㅎ,,,

2024-10-25 14:05 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/user/domain/User.java
> +  @OneToOne(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
이것은.. 맞는말같습니다..
도메인 설계 관점에서도 유저가 가지고있는게 맞고, 로직도 유저 위주로 동작하고, null이야 어떻게든 처리가 가능할테니....
JPA 쓰는 이유 그자체네요.....

2024-10-25 14:09 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
**진담 95%**: 사실 Claude 친구도 Long 유지하라하고 저도 코드 엎고싶지 않았는데,,,,,
  - DB를 바꾸는 것을 극도로 두려워했던 것이 첫번째 이유이고,
  - 2시간정도 레전드로 많이 발생한 타입에러에 곱게 DB를 바꾸려했는데 이미 너무 멀리 와버린 상황이었습니다.

마음이 아프네요

2024-10-25 14:43 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
근데 DB를 바꾸는게 무슨말이쥬? 쿼리만 바꾸면되지않나유

2024-10-26 06:08 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
쿼리만 바꾼다는게 무슨뜻이죠..?

2024-10-26 06:17 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
데이터베이스 ddl만 바꾸면 딸깍아닌가???라는 생각

2024-10-26 06:20 UTC, ekgns33 commented on src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
>  public final class UserFixtures {
어라 근데 이렇게하면 무조건 레포지토리에 저장을 해야해요.. 멤버가 이미 저장된 상태라고 치는건데. 
저는 테스트코드에서 그 작업은 해결해야하는 것 같습니다. 여기서 이렇게하면 테스트간의 의존성이 생기게됩니다.

2024-10-26 06:21 UTC, ekgns33 requested changes
@hughesgoon 고생하셨습니다. UserFixture쪽은 레포지토리를 연동하는게 좋아보이지 않습니다.
테스트의 펑티모를 방지하기 위한 임시방편이라면 제가 처리해보겠습니다

2024-10-26 06:25 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
그게 DB를 바꾼다는 말 아닌가요?
물론 DDL 바꾸는게(테이블 타입 바꾸는게) 간단한게 맞습니다. 솔직히 타입 바꿀까 싶었던것도 사실이고요.

그러나 저희 ERD는 엔티티 연관관계 뿐 아니라 타입까지 포함해 굉장히 오랜기간 여러 토의를 거치며 의결된 사안입니다.
Long 유지하기 위해 역으로 DB 타입을 바꾼다는건 말이 안됩니다.

> BigInt를 쓰지 않는 이유는 위에 한번 더 언급했습니다.
> 
> Long이 범위가 넓고 요즘 디스크 비용도 싼건 사실인데요. 이걸 불러와서 쓸 RAM이나 캐시나 기타 메모리들의 비용은 싸지 않습니다. 몇바이트 차이지만 안쓸거 굳이 감수할 이유가 없다에 가까워요.
> 그렇다고 tiny같은 슈퍼 최적화까진 오바인 것 같고, int가 무난무난한 선인 것 같았어요.
> int는 21억, unsigned하면 42억개까지 가능하고, 대다수의 서비스는 이것을 넘지 않을 것입니다.
> 또한, 이것이 넘을즈음이 다가오면 이 칼럼들을 비롯해 DB를 마이그레이션할 여유는 있을 것 같습니다.

2024-10-26 06:29 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
1. 논의가 아닌 의결이기에 강박적으로 지키려 했다.
2. (설령 본인이 관리하더라도) 코드 외 영역인 DB, 혹은 인프라를 수정하는것은 절대 좋은 습관이 아니다.

요런 의도로 이해해주면 되겠습니다 ㅎㅅㅎ..

2024-10-26 06:34 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
@hughesgoon  아하 전 그 의미가 아니라 그 디비 바꾸는게 고민하는게 아니라 진짜로 타입바꾸는게 어려운건가 했었어욬ㅋㅋㅋㅋ 직접 들어가서 막 다 뜯어고치고 해야하는줄

2024-10-26 06:34 UTC, hughesgoon commented on src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
>  public final class UserFixtures {
이부분이 이제 profile 역 연관관계로 인해 발생한 사고....라 임시방편 처리한게 맞습니다.

JPA의 특성상 User객체가 DB에 반영되기 전까지 id가 생성되질 않습니다.
이렇게되면 profile 객체에서 의존관계 삽입이 불가능해요. 다른말로 아예 DB 제약위반으로 테스트 setup단계에서 실패하게 됩니다.

user객체의 id를 고정시키고, profile에 이를 반영해 생성할 좋은 방법이 있다면 수정하겠습니다.

2024-10-26 06:38 UTC, ekgns33 commented on src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
>  public final class UserFixtures {
1. 실제 비즈니스에서는 그냥 객체를 만들면 생성됩니다 연관관계 주인이 User라서요
2. 테스트에서는 `ReflectionTestUtils.setField`를 사용하면 됩니다. (생성자를 여는것을 막았죵)

```
@Nested
    @DisplayName("유저를 입력으로 받았을 때")
    class Context_with_valid_arguments {
      User participant = UserFixtures.getDefaultUser();

      @Test
      @DisplayName("참가자목록에 유저 ID를 추가한다")
      void it_adds_a_participant() {
        ReflectionTestUtils.setField(participant, "id", 1L);
        running.addParticipant(participant);
        assertTrue(running.hasParticipant(participant));
      }
    }
```

2024-10-26 06:39 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/running/domain/record/PersonalRecord.java
> +  private Integer id;
DB관리자 김현재씨와 코드작성자 김현재씨의 인격이 분리되어 모두 거부하고있다고 생각하면 편합니다 🙄
군 복무 이후로 생겨버린 업무별 인격 멀티프로필;; ALTER 싫어~~

2024-10-26 06:44 UTC, hughesgoon commented on src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
>  public final class UserFixtures {
테이블과 엔티티에서의 주권이 달라서인지 실행할때 자꾸 오류터지더라고요;
음,, 어차피 테스트로 고정된 객체니 임의로 칼럼 넣는 방식일까요 🤔

2024-10-26 06:55 UTC, ekgns33 commented on src/test/java/com/run_us/server/domains/user/domain/UserFixtures.java
>  public final class UserFixtures {
가상의 컬럼이 있다고 생각한다가 맞겠죠? 저는 유닛 테스트에서 객체들만 가지고 로직을 테스트하기에 보통 fixture을 직접 만들어서 사용하거나 생성자에 포함되지 않는 id만 리플렉션으로 주입해서 사용했습니다.
도메인 유닛테스트라면 굳이 데이터베이스에 넣을 필요도 없기에 상관없어보입니다. 디비테스트나 통합테스트할때는 특정상황을 setup에서 맞춰주고 매 테스트마다 auto increment를 없애주거나 아예 지우는 식으로 의존성을 끊더라구요

2024-10-29 03:42 UTC, ekgns33 approved these changes

2024-10-29 05:48 UTC, merged