[Refactor/get user] 소켓 통신 시 유저정보 가져오는 로직 변경 +작은 리팩토링들, 로깅 룰 제안
Run-Us/Run-Us-server pull request #38
Opened 2024-10-25 18:35 UTC by jeeheaG

### 연관된 이슈를 적어주세요 📌
close #27

### 작업한 내용을 설명해주세요 ✔️
-  : DB가 아닌 세션에서 가져오는 로직으로 변경
- 그 외 리팩토링 사항들
    - StompIntercpetor 위치 global.config 로 변경
    - 이름 변경 SocketExceptionCustomHandler ->SocketExceptionCustomInterceptor
    - "/queue/log" 상수화

### 트러블 슈팅

### 리뷰어에게 하고 싶은 말을 적어주세요

[로깅 룰 제안]

RunningResultService의 saveRunningResult() 에서 RunningException.of(RunningErrorCode.RUNNING_NOT_FOUND) 를 단지고 있는데,
호출하는 컨트롤러쪽에서 이 메서드에서 발생하는 모든 에러를 잡아서 RunningErrorCode.AGGREGATE_FAILED) 로 바꿔서 응답해주고 있어서 (로그도 안찍고 있는 상황)
원래 발생한 에러가 뭐였는지 파악할 수 없는 상태라
개선이 필요할 것 같아요

이런 상황과 관련해
두가지 룰을 제안합니다!
- 모든 컨트롤러, 서비스의 각 API별 큼직한 메서드들은 맨 첫 줄에 로그 찍고 시작하기. (내부 호출 메서드들은 선택)
    - 형식 예시
    [API] RunningController.메서드명() called
    [SERVICE] RunningService.메서드명() called
- 예외 throw 또는 catch 시 어떤 예외인지 서버 로그 남기기
그리고
- +메서드마다 javadoc으로 설명 한줄씩은 써주기

로그로 최소한의 요청 흐름을 알 수 있게 하기 위해 제안합니다.
다른 의견 얼마든지 주세요!

### 확인하기

- [ ] : 코드에 에러가 없는지 확인했나요?
- [ ] : PR에 설명을 기재했나요?
- [ ] : PR 태그를 붙였나요?
- [ ] : 불필요한 로그나 `System.out`을 제거했나요?

2024-10-26 01:53 UTC, ekgns33 requested changes
너무 고생하셨어요! 질문 몇개달아놨습니다.

그리고 로깅 관련해서는 계층별로 로그를 찍으면 상세하게 로그를 분석할 수 있을 것 같은데 요청에 종속되어야하기에 바인딩을하거나 하면 좋을 것 같네요. 
- "로그를 찍어야하는가?" 이건 제 생각이지만 시스템에서 추적을 할필요가 있는 부분에서 찍으면 될 것 같습니다. 계층별로 다 다는 것은 무분별할 수 있지 않을까 생각이 되네요. (그래도 찍다보면 계층에 하나씩 찍겠죠?)
- 개인정보는 로그에 찍으면 안될 것 같습니다! publicId같은 공개 가능한 정보만 적는거루~

2024-10-26 01:53 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +    // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
TODO 지워주세요~

2024-10-26 01:53 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +
에러코드에 로그메세지 필드가 있는데 여기서 if문으로 처리하신 이유가 있을까요?
`StompErrorHandler`에 log.err을 추가하는게 어떨지 궁금합니다.

2024-10-26 01:53 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +      sendToUser(sessionId, USER_WS_LOGS_SUBSCRIBE_PATH, ErrorResponse.of(RunningErrorCode.AGGREGATE_FAILED));
이 코드는 ErrorHandler가 없을 때 에러처리할 부분이 없어서 해당 방법으로 사용한 코드입니다. 이제는 소켓 요청에서 발생한 에러를 핸들러에서 처리하니 필요없을 것 같아요

2024-10-26 01:53 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
> +    log.info("saveRunningResult : runningId : {}, user : {}", runningId, user);
혹시 이거 로그가 어떻게 찍히나요? user를 그대로 넣어서 질문합니다

2024-10-26 01:53 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/config/StompInterceptor.java
> +        // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
`SUBSCRIBE` 부분에서도 `CONNECT`에서 설정한 정보를 사용할 수 있도록 작성해주셨군요! 그런데 여기서 더블체크해야하는 이유가 있나염??

2024-10-26 17:03 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +
아 그렇게 해야겠네요 바꾸겠습니다!

2024-10-26 17:05 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +      sendToUser(sessionId, USER_WS_LOGS_SUBSCRIBE_PATH, ErrorResponse.of(RunningErrorCode.AGGREGATE_FAILED));
그럼 try catch 문 아예 지울게요~

2024-10-26 17:08 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/service/RunningResultService.java
> +    log.info("saveRunningResult : runningId : {}, user : {}", runningId, user);
User 에 ToString 어노테이션 달아놔서 User(id=1, ...) 이런식으로 찍힙니다.
근데 이 로그는 꼭 필요한 건 아닌것같네요..? 지우겠습니다

2024-10-26 17:10 UTC, jeeheaG commented on src/main/java/com/run_us/server/global/config/StompInterceptor.java
> +        // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
더블체크가 Optional 로 nullable 확인한 거 말씀하시는 걸까요??

2024-10-26 17:11 UTC, jeeheaG commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +    // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
이거 아직 해결 안된 TODO 들인데, 해결 후에 머지했으면 하시나요?
> // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
이거는 예외날리는 로직이 현재 중복적이라는 의미로 작성했슴다!

2024-10-26 17:38 UTC, jeeheaG commented
로그는 계층별 하나 정도가 저도 적당하다고 생각합니다! 나머지도 동의해요~

2024-10-27 02:01 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/running/controller/RunningSocketController.java
> +    // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
아하 전 해결된 이슈인줄 알았네요! 그냥두시죠

2024-10-27 06:10 UTC, ekgns33 commented on src/main/java/com/run_us/server/global/config/StompInterceptor.java
> +        // TODO : 중복 로직 - 세션 유저 정보 가져와서 null 이면 예외날리기
넴!

2024-10-27 14:10 UTC, ekgns33 approved these changes
머지할까용?

2024-10-28 07:24 UTC, merged