[Feat/crew join request process] - 크루 가입요청 생성 및 취소
Run-Us/Run-Us-server pull request #63
Opened 2024-12-18 15:40 UTC by hughesgoon

### 연관된 이슈를 적어주세요 📌

JIS-107

### 작업한 내용을 설명해주세요 ✔️

> 어딘가 이상한건 아는데, 코드 컨벤션이 크게 바꼈다보니 피드백 받는용으로 초안 빨리 올려봅니다.
> JIS-107은 가입요청과 취소 2가지를 구현해야하는데, 우선 요청까지만 푸시했고, 취소는 피드백 이후 업데이트 예정입니다.

- 현재 로그인한 사용자 정보를 받아오기 위한 `@CurrentUser` 어노테이션 구현
  - PublicId와 InternalId만을 가지는 가벼운 객체인 UserPrincipal 생성
  - Security의 책임과 User-Auth 강결합 구조 사이에서 타협해서 UserIdResolver에게 예외적인 UserRepository 적용
  - 컨트롤러에서 `@CurrentUser UserPrincipal userPrincipal` 형식으로 사용하면 됩니다.
- 크루 가입요청 엔드포인트 구현
  - 외부 노출경계인 컨트롤러만 userPublicId 정보 활용 / 내부 로직부터는 userInternalId만 사용
  - 이로인해
    - 내부용 DTO `CrewJoinRequestInternalResponse` 분리
    - useCase가 아닌 컨트롤러가 SuccessResponse 생성
  - 상세사유
    - UseCase부터는 순수한 비즈니스 로직을 담당하기에 userInternalId가 타당
    - userPrincipal 객체는 웹 계층의 구현이기에, ID 변환의 책임은 표현계층은 컨트롤러에게 있음

### 리뷰어에게 하고 싶은 말을 적어주세요

- 아직도 UseCase와 Service의 명확한 구분을 모르겠읍니다,,, Somebody help me

2024-12-18 16:31 UTC, ekgns33 approved these changes
고생하셨습니다! UseCase는 여러 도메인간의 의존을 모으고 각 도메인 끼리는 의존을 끊어주기 위한 레이어라고 보시는게 좋을 것 같아요. 지금코드에서도 Crew만의 도메인 로직을 수행하는 부분은 CrewService에서 수행하고 UseCase에서는 필요한 정보만 넘겨주는 식으로 작성되었는데 제 의도와 일치하는 것 같아요.

2024-12-19 05:56 UTC, hughesgoon commented
리뷰 반영하고, 가입요청 취소 구현체도 추가로 업로드 했습니다~
JoinRequest는 엔티티가 아니다보니 CrewRepository에 JOIN 쿼리 넣어서 조회 넣어놨습니다.
@ekgns33 @jeeheaG

2024-12-19 06:15 UTC, ekgns33 requested changes
고생하셨어요!

2024-12-19 06:15 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
> +    private final CrewRepository crewRepository;
CrewRepository를 사용하지 않는것 같습니다!

2024-12-19 06:15 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/crew/domain/Crew.java
> +    public boolean hasWaitingRequest(Integer userId) {
N+1이 발생하는지 한번 확인해주세요! 
특정 값을 조회할때는 join을 사용하는데 크루가 직접찾을때 lazy로 조회할때 문제가 될 수도 있겠네요

2024-12-19 06:48 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/crew/domain/Crew.java
> +    public boolean hasWaitingRequest(Integer userId) {
요거 엄,, 도메인 로직이라 엔티티에 몰아주다 발생한 일인데요.
수정한다면 대충 이런 느낌이지 않을지.... 어케해야할까 싶긴하네요. @ekgns33 
1. Repository에 존재여부 확인하는 쿼리 만들고 Validator에서 Repository 활용
2. 아예 최적화 관점에서 DDD를 쪼금 깨더라도, ValidationDto 만들고, Repository에서 Validation 한번에 수행하는 쿼리 구현하기

2024-12-19 06:49 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/crew/service/CrewValidator.java
> +    private final CrewRepository crewRepository;
요건 위쪽 hasWaitingRequest 이슈와 연관되는거라, 결론나는대로 연결 수정하겠슴당

2024-12-19 06:52 UTC, hughesgoon commented on src/main/java/com/run_us/server/domains/crew/domain/Crew.java
> +    public boolean hasWaitingRequest(Integer userId) {
참고: 현재 가입요청에 대한 Validation Rule은 아래 3가지입니다.
1. 이미 가입된 상태인지?
2. 이미 제출한 요청이 있는지?(중복인지) <- 이슈가 된 부분
3. 크루가 활성 상태가 맞는지?

2024-12-19 07:16 UTC, ekgns33 commented on src/main/java/com/run_us/server/domains/crew/domain/Crew.java
> +    public boolean hasWaitingRequest(Integer userId) {
> 가입 거절된 경우, 신청일 기준 한 달 후 재신청 가능. 
위의 정책사항이 있는데요. 저친구를 만족하려면 거절된 요청들은 저장을 해야겠네요. 
`@ElementCollection`을 Set으로 두고, 거절된 요청을 저장하는 Set을 하나 더 두는건 어떨까요? 테이블이 하나 더 생기긴하겠네요.

결국 기존의 방식도 쿼리가 날라가는 것을 막을 수 있는 것은 아니니 1번 2번 둘다 괜찮아보입니다! 편한데로 해주세요!

2024-12-21 10:33 UTC, hughesgoon commented
joinRequest 검증 로직 수정하고 CANCELED 상태 추가했습니다.

크루 자체는 독립적으로 존재하는 리소스라서 생성되고 삭제되는 라이프사이클을 가지지만,
가입 요청은 프로세스의 기록이자 결과를 나타내다보니 deletedAt 방식이 아니라 status.CANCELED로 soft delete했습니다.

2024-12-21 16:13 UTC, jeeheaG approved these changes
고생하셨습니다! 어노테이션 구성 감사해요
Response 를 만드는 위치에 대해서
저는 다훈님이랑 얘기도 해보고 기존 코드도 참고해서 UsercaseImpl 에서 만들게 작성하고있는데,
하나로 통일하면 좋을 것 같아요.

2024-12-21 16:30 UTC, hughesgoon commented
전체적으로 통일해야 한다는 점 동의합니다. 스레드파서 얘기해보고 리팩토링 티켓 끊어서 추후에 고쳐보는건 어떨까요?

일단 제 의도는 `외부통로(컨트롤러) | 로직(유즈케이스, 서비스) | DB 인프라(레포지토리)`의 분리였습니다.
PublicId는 표현계층인 컨트롤러만 쓰도록 하고, 로직은 InternalId로 하려했어요.

그치만 사실 더 중요한 가치는 통일성일지 모르겠습니다. 유즈케이스에 UserPrincipal 객체 자체를 넘겨볼까요?


> - 크루 가입요청 엔드포인트 구현
>   - 외부 노출경계인 컨트롤러만 userPublicId 정보 활용 / 내부 로직부터는 userInternalId만 사용
>   - 이로인해
>     - 내부용 DTO `CrewJoinRequestInternalResponse` 분리
>     - useCase가 아닌 컨트롤러가 SuccessResponse 생성
>   - 상세사유
>     - UseCase부터는 순수한 비즈니스 로직을 담당하기에 userInternalId가 타당
>     - userPrincipal 객체는 웹 계층의 구현이기에, ID 변환의 책임은 표현계층인 컨트롤러에게 있음

2024-12-23 02:59 UTC, jeeheaG commented
오 알겠습니다 id 사용영역 구분하시려고 그것만 다른 dto 를 두개 만드신 거군요,, 처음에 놓쳤었네요..!
이 부분은 효율적으로 가냐 vs 경계 확실히 하냐 로 장단점이 갈리는 것 같아서 
말씀드렸던 대로 하나로 통일만 되면 좋을 것 같습니다.
디코에 스레드 만들어져 있는 것 같으니 거기서 이야기하면 될 것 같네요! 고생많으셨어요

2024-12-24 10:34 UTC, ekgns33 approved these changes

2024-12-25 08:35 UTC, merged